### ISSUE TITLE
Works like magic!

### ISSUE THREAD

**Issue by tediorelee** [bkahlert/kill-zscaler#1]
Just to open this issue to tell how much happy I am! been struggling with Zscaler since I joined this company, thanks a lot!

**Comment by ghost** [comment]
Thank you @bkahlert to save hour of works without fuck up my brain for every single working project ❤️

**Comment by bkahlert** [comment]
@tediorelee @matteo-fantin Thank you for your feedback. I'm glad to hear I could help and that investing the time in sharing my stuff was not in vain!

**Comment by Teo230** [comment]
> @tediorelee @matteo-fantin Thank you for your feedback. I'm glad to hear I could help and that investing the time in sharing my stuff was not in vain!

I have bad news, our company just blocked the github link project and application on MacOS. Luckly, the shell command works, I think they block the application, not the script (I want to see if our company block the shell process what could happend 😂)
