### ISSUE TITLE
Where to set the SHARE_ZSCALER_HOSTS

### ISSUE THREAD

**Issue by deepjyotiray** [bkahlert/kill-zscaler#5]
Where to set the SHARE_ZSCALER_HOSTS in MacOS Parallel VM

**Comment by bkahlert** [comment]
You don't set the env variable in the VM but on the machine that you would like to use the ZScaler tunnel established in the VM. https://github.com/bkahlert/kill-zscaler/blob/main/share-zscaler.sh#L24 shows an example.

But I strongly recommend to use https://github.com/bkahlert/kill-zscaler/blob/main/share-zscaler.v2.sh.
There you need to specify far less manually. Most parameters are resolved automatically.
